image: node:latest

stages:
  - build
  - deploy
cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
stage_deploy:
  stage: deploy
  artifacts:
    paths:
      - build/
  script:
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
    - scp -P22 -r build/* root@www.sgwebdesigns.com:/tmp
