image: node:latest

stages:
  - build
cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
build_nextjs:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/
export_nextjs:
  stage: build
  script:
    - npm run export
  artifacts:
    paths:
      - out/